[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[lib]
name = "proto"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
rmp-serde = "1.3.0" # msgpack
serde_json = "1.0.145"
anyhow = "1.0.100"
