[package]
name = "plugins_sdk"
version = "0.1.0"
edition = "2024"

[lib]
name = "plugins_sdk"
crate-type = ["rlib", "cdylib"]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
anyhow = "1.0.100"
libc = "0.2.177"
