[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.33.2"
eframe = "0.33.2"
anyhow = "1.0.100"
core = {path = "../core"}
chrono = "0.4.42"
pnet = { version = "0.35", features = ["std"] }
httparse = "1.10.1"

[lib]
name = "ui"
path = "src/lib.rs"
